// Copyright 2026 Justin Black
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using Waypoint.Core.Trust;
using Waypoint.Tests.Support;
using Xunit;

namespace Waypoint.Tests.Core.Trust;

/// <summary>
/// Issue #753's upload-validation matrix AC, proven against
/// <see cref="TrustBundleValidator"/> directly (pure, no I/O). Every certificate here
/// is freshly generated by <see cref="InventedCertificateFactory"/> for a
/// <c>*.example.internal</c> subject -- never real or captured CA material.
/// </summary>
public sealed class TrustBundleValidatorTests
{
	[Fact]
	public void Validate_accepts_a_single_valid_certificate()
	{
		string pem = InventedCertificateFactory.CreateSelfSignedPem("ca.example.internal");

		TrustBundleValidationResult result = TrustBundleValidator.Validate("My CA", pem, DateTimeOffset.UtcNow);

		Assert.True(result.IsValid);
		Assert.Equal(TrustBundleValidationOutcome.Valid, result.Outcome);
		Assert.Equal("My CA", result.Label);
		Assert.Contains("ca.example.internal", result.Subject);
		Assert.NotNull(result.FingerprintSha256);
		Assert.Equal(64, result.FingerprintSha256!.Length);
		Assert.Matches("^[0-9a-f]{64}$", result.FingerprintSha256);
	}

	[Fact]
	public void Validate_accepts_a_multi_certificate_chain_and_uses_the_leaf()
	{
		string pem = InventedCertificateFactory.CreateSelfSignedChainPem("leaf.example.internal", "issuer.example.internal");

		TrustBundleValidationResult result = TrustBundleValidator.Validate(null, pem, DateTimeOffset.UtcNow);

		Assert.True(result.IsValid);
		Assert.Contains("leaf.example.internal", result.Subject);
		// No label supplied: falls back to the leaf's own subject (not the issuer's).
		Assert.Contains("leaf.example.internal", result.Label);
	}

	[Theory]
	[InlineData(null)]
	[InlineData("")]
	[InlineData("   ")]
	public void Validate_rejects_empty_input(string? pem)
	{
		TrustBundleValidationResult result = TrustBundleValidator.Validate("label", pem, DateTimeOffset.UtcNow);

		Assert.False(result.IsValid);
		Assert.Equal(TrustBundleValidationOutcome.Empty, result.Outcome);
		Assert.Null(result.PemChain);
	}

	[Fact]
	public void Validate_rejects_oversized_input()
	{
		string oversized = "-----BEGIN CERTIFICATE-----\n" + new string('A', TrustBundleValidator.MaxPemBytes + 1) + "\n-----END CERTIFICATE-----\n";

		TrustBundleValidationResult result = TrustBundleValidator.Validate("label", oversized, DateTimeOffset.UtcNow);

		Assert.False(result.IsValid);
		Assert.Equal(TrustBundleValidationOutcome.OversizedInput, result.Outcome);
		Assert.Null(result.PemChain);
	}

	[Theory]
	[InlineData("not a certificate at all")]
	[InlineData("-----BEGIN CERTIFICATE-----\nnot-valid-base64!!!\n-----END CERTIFICATE-----\n")]
	[InlineData("-----BEGIN CERTIFICATE-----\nAAAA\n")] // unterminated block
	public void Validate_rejects_malformed_input(string malformed)
	{
		TrustBundleValidationResult result = TrustBundleValidator.Validate("label", malformed, DateTimeOffset.UtcNow);

		Assert.False(result.IsValid);
		Assert.Equal(TrustBundleValidationOutcome.Malformed, result.Outcome);
		Assert.Null(result.PemChain);
		Assert.NotNull(result.SafeErrorMessage);
	}

	[Fact]
	public void Validate_rejects_an_expired_certificate()
	{
		string pem = InventedCertificateFactory.CreateExpiredSelfSignedPem();

		TrustBundleValidationResult result = TrustBundleValidator.Validate("label", pem, DateTimeOffset.UtcNow);

		Assert.False(result.IsValid);
		Assert.Equal(TrustBundleValidationOutcome.Expired, result.Outcome);
		Assert.Null(result.PemChain);
	}

	[Fact]
	public void Validate_rejects_a_bare_private_key()
	{
		string key = InventedCertificateFactory.CreateInventedPrivateKeyPem();

		TrustBundleValidationResult result = TrustBundleValidator.Validate("label", key, DateTimeOffset.UtcNow);

		Assert.False(result.IsValid);
		Assert.Equal(TrustBundleValidationOutcome.ContainsPrivateKey, result.Outcome);
		Assert.Null(result.PemChain);
	}

	[Fact]
	public void Validate_rejects_a_valid_certificate_with_an_embedded_private_key()
	{
		// A mixed upload (real chain + embedded key) must be rejected WHOLESALE, not
		// silently split into "keep the cert, drop the key" -- issue #753 AC.
		string mixed = InventedCertificateFactory.CreateSelfSignedPem("ca.example.internal") + "\n" + InventedCertificateFactory.CreateInventedPrivateKeyPem();

		TrustBundleValidationResult result = TrustBundleValidator.Validate("label", mixed, DateTimeOffset.UtcNow);

		Assert.False(result.IsValid);
		Assert.Equal(TrustBundleValidationOutcome.ContainsPrivateKey, result.Outcome);
		Assert.Null(result.PemChain);
	}

	[Fact]
	public void Validate_never_echoes_submitted_text_in_the_error_message_for_malformed_input()
	{
		const string secretLookingPayload = "TOTALLY-NOT-A-CERT-super-secret-marker-xyz";
		string malformed = $"-----BEGIN CERTIFICATE-----\n{secretLookingPayload}\n-----END CERTIFICATE-----\n";

		TrustBundleValidationResult result = TrustBundleValidator.Validate("label", malformed, DateTimeOffset.UtcNow);

		Assert.False(result.IsValid);
		Assert.DoesNotContain(secretLookingPayload, result.SafeErrorMessage);
	}
}
